# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-OnlinePayment-IPPay
version:      0.03
version_from: IPPay.pm
installdirs:  site
requires:
    Business::OnlinePayment:       3
    Business::OnlinePayment::HTTPS: 0.09
    Test::More:                    0.42
    Tie::IxHash:                   0
    XML::Simple:                   0
    XML::Writer:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
