---
abstract: unknown
author:
  - 'Ivan Kohler <ivan-ippay@freeside.biz>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-OnlinePayment-IPPay
no_index:
  directory:
    - t
    - inc
requires:
  Business::OnlinePayment: 3
  Business::OnlinePayment::HTTPS: 0.09
  Locale::Country: 2
  Test::More: 0.42
  Tie::IxHash: 0
  XML::Simple: 0
  XML::Writer: 0
version: 0.09
